from fpdf import FPDF
from urllib.parse import quote

def main():
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 12, "NGS Advisor Example Report", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 8, "Scenario: Bulk RNA-seq on Zea mays to assess gene expression under salt treatment vs control.", ln=True)
    pdf.ln(4)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[RECOMMENDATION]", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "Route: Bulk RNA-seq (PE, stranded, PolyA) for Zea mays, comparing salt-treated vs control.\nReason: Differential expression is the goal; bulk RNA-seq is cost-effective and interpretable; prioritize biological replicates and batch randomization.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[BUDGET_TIERS]", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "- Tier A (minimal): n=3 per condition; >=20M read pairs/sample; PE150; stranded PolyA. Answers main DE but limited for small effects.\n- Tier B (recommended): n=4-5 per condition; ~40M read pairs/sample; PE150; stranded PolyA; randomize library prep and lanes. Best value, more stable statistics.\n- Tier C (higher budget): n>=6 per condition; ~60M read pairs/sample; optionally add timepoints or treatment gradients. Improves small-effect detection and resolution.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[PARAMETERS]", ln=True)
    pdf.set_font("Arial", '', 11)
    reads_b = 40_000_000
    read_len = 150
    data_gb_b = reads_b * read_len * 2 / 1e9
    pdf.multi_cell(0, 6, f"Read length: PE150 | Why: common and cost-effective.\nReads per sample: ~40M read pairs | Why: balances cost and statistical power for plant samples.\nLibrary type: stranded PolyA; if FFPE or degraded RNA, use 3' end strategy.\nBiological replicates: two conditions (control/salt), prioritize replicate count.\nConversions: Reads(pairs) ~= Data_Gb*1e9/(read_len*2); Data_Gb ~= Reads(pairs)*read_len*2/1e9.\nExample (Tier B): 40M pairs x150x2 ~= {data_gb_b:.1f} Gb per sample.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[PITFALLS]", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "1) Batch confounding: library prep or lane batches may mask treatment effects. Avoid: randomize samples across prep and lanes; record batch factors for downstream correction.\n2) RNA quality fluctuation under stress. Avoid: pre-QC (RIN/DV200), use 3' end or rRNA depletion if needed.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[QC_LINES]", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "Mapping rate >=70%; rRNA fraction <=10%; moderate duplication; uniform gene body coverage. If abnormal, check sample quality and library first.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[DECISION_LOG]", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, "Assumption: PolyA is suitable and effect sizes are moderate; if targeting non-PolyA transcripts or very small effects, switch to rRNA depletion and increase replicates/reads.")
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[PUBMED_QUERY]", ln=True)
    pdf.set_font("Arial", '', 11)
    query = '("RNA-seq"[MeSH] OR "transcriptome sequencing"[tiab]) AND ("Zea mays"[tiab] OR maize[tiab]) AND ("salt stress"[tiab] OR "salt tolerance"[tiab]) AND ("2022"[pdat] : "2026"[pdat])'
    pdf.multi_cell(0, 6, query)
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 13)
    pdf.cell(0, 8, "[PUBMED_URL]", ln=True)
    pdf.set_font("Arial", '', 11)
    url = "https://pubmed.ncbi.nlm.nih.gov/?term=" + quote(query)
    pdf.set_text_color(0, 0, 255)
    pdf.write(7, url, url)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5, "Note: Numbers are indicative; confirm with literature and vendor support. Do not fabricate PMIDs. For finalized PDF delivery, trigger on request.")
    pdf.output("ngs_advisor_example_maize_salt_bulkRNA.pdf")

if __name__ == "__main__":
    main()
